apiVersion: v1
kind: Service
metadata:
  namespace: coredns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ns.kube.technotut.net
spec:
  selector:
    app: coredns
  type: LoadBalancer
  loadBalancerIP: 10.1.0.254
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP