apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: coredns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.4.34
          command:
            - /usr/local/bin/etcd
            - --name
            - etcd
            - --data-dir
            - /etcd-data
            - --listen-client-urls
            - http://0.0.0.0:2379
            - --advertise-client-urls
            - http://0.0.0.0:2379
            - --listen-peer-urls
            - http://0.0.0.0:2380
            - --initial-advertise-peer-urls
            - http://0.0.0.0:2380
            - --initial-cluster-token
            - etcd-cluster
            - --initial-cluster-state
            - new
            - --log-level
            - info
            - --logger
            - zap
            - --log-outputs
            - stderr
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
      volumes:
        - name: etcd-data