apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |-
    # global config
    global:
      scrape_interval: 15s 
      evaluation_interval: 15s 

    scrape_configs:
    - job_name: 'network'
      static_configs:
      - targets: 
        - 192.168.16.1
        - 192.168.99.1
        - 192.168.99.2
        - 192.168.99.4
        - 192.168.99.5
        - 192.168.99.6
        - 192.168.99.254
      metrics_path: /snmp
      params:
        module: [nec]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: snmp-exporter-service.monitoring.svc.cluster.local:9116
    - job_name: 'srv_node'
      static_configs:
        - targets: ['192.168.99.99:9100','192.168.99.100:9100']
    - job_name: 'vj_system'
      static_configs:
        - targets: ['192.168.20.100:9182']
    - job_name: 'ndi_system'
      static_configs:
        - targets: ['192.168.20.201:9100','192.168.20.202:9100','192.168.20.203:9100']
    - job_name: 'kubernetes-nodes'
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)