apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp-deployment
  labels:
    app: rtmp-live-server
  namespace: live
spec:
  selector:
    matchLabels:
      app: rtmp-live-server
  replicas: 2
  template:
    metadata:
      labels:
        app: rtmp-live-server
    spec:
      containers:
      - name: rtmp-live-server
        image: ghcr.io/technotut/rtmp-live-server:main
        ports:
        - containerPort: 1935
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 256Mi
      restartPolicy: Always
status: {}