apiVersion: v1
kind: Service
metadata:
  name: rtmp-service
  labels:
    app: rtmp-live-server
  namespace: live
spec:
  selector:
    app: rtmp-live-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
    - protocol: TCP
      port: 8080
      targetPort: 8080