repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: freeipa-dns-sync
    namespace: external-dns
    chart: bitnami/external-dns
    installed: true
    values:
      - provider: rfc2136
        logFormat: json
        domainFilters:
          - kube.technotut.net
        rfc2136:
          host: kube.intra.technotut.net
          zone: kube.technotut.net
          tsigKeyname: externaldns
          tsigSecretAlg: hmac-sha256
          secretName: freeipa-rfc2136