apiVersion: v1
kind: Service
metadata:
  name: cam1-dns-service
  labels:
    app: cam1-sonycam-dns
  namespace: cam1
spec:
  selector:
    app: cam1-sonycam-dns
  type: LoadBalancer
  loadBalancerIP: 10.33.71.11
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53